### ISSUE TITLE
Make sure we inform about reST and Docutils in general

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#10]
### Situation
The basics of reStructureText are documented in the context of 'docutils' and 'reStructureText'.

Pointers to those topics are given here: https://docs.typo3.org/typo3cms/drafts/github/T3DocumentationStarter/Public-Info-000/Knowledgebase/HowToDocument/reStructuredText/Index.html#learn-about-the-basics-of-restructuredtext

### Task
We, I, should check that that content is part of this repository as well.

### Remark
For whatever reason the fundamental reST documentation, for example about the reStructuredText syntax, never got styled. It's hard to read and you'll end up with something like this: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#tables Nevertheless, this is still the authoritative single point of truth.

**Comment by susannemoog** [comment]
@marble will you please take care of this issue?

**Comment by linawolf** [comment]
This can be closed as we will switch to php based rendering
