### ISSUE TITLE
Document how to link to changelog

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#110]
[Slack](https://typo3.slack.com/archives/C028JEPJL/p1562247666384000)

From Martin:

① In the CoreApi manual define a mapping in Settings.cfg:

```
[intersphinx_mapping]
t3core = https://docs.typo3.org/c/typo3/cms-core/master/en-us/
```

② Use this link:

```:doc:`t3core:Changelog/8.1/Deprecation-75625-DeprecatedCacheClearingOptions```

This target key is made up of: ⓐ url-mapping-key ⓑ ':' ⓒ relative path ⓓ slug of the document title

The slug is [A-Za-z0-9-_] only, case insensitive. The first title in a reST file is its document title, which is transformed into the slug (=key).

③ Result:
The proper doctitle is shown like
![image](https://user-images.githubusercontent.com/307057/60713980-5e34de80-9f1a-11e9-8419-e23195424ea4.png)

# Related

* core issue: https://forge.typo3.org/issues/89330
* decisions: https://decisions.typo3.org/t/done-handle-changelog-vs-main-documentation-for-features/518

**Comment by sypets** [comment]
It is - of course - also possible to add labels to the changelog. But first, this should be decided in general, along with several other things. See other issues. I am currently working on creating a proposal.

See also

* https://github.com/TYPO3-Documentation/T3DocTeam/issues/76
* https://github.com/TYPO3-Documentation/T3DocTeam/issues/75

**Comment by marble** [comment]
## For freaks only

### Example
Q: How do I know whether there is a label containing '75625' in the core changelog?

A: The docker container can give us that answer:
```
➜  docker run --rm -t --entrypoint /bin/bash t3docs/render-documentation:v2.2.6 -c "pipenv run python -m sphinx.ext.intersphinx https://docs.typo3.org/c/typo3/cms-core/master/en-us/objects.inv" | grep 75625
	Changelog/8.1/Deprecation-75625-DeprecatedCacheClearingOptions Deprecation: #75625 - Deprecated cache clearing options: Changelog/8.1/Deprecation-75625-DeprecatedCacheClearingOptions.html

➜  # So the answer is: Changelog/8.1/Deprecation-75625-DeprecatedCacheClearingOptions Deprecation
```

### Explanation
What's going on here?

`docker run t3docs/render-documentation:v2.2.6`
We run our Docker container.

`--rm`
We want that container removed right afterwards.

`-t`
We connect the output to our terminal.

`--entrypoint /bin/bash`
We specify the bash as shell. Don't put the command to execute here!

`-c`
For the bash we specify that the following is a command to be executed.

`pipenv run python`
Inside the container `/ALL/venv` is our current folder. A Python virtual environment is prepared in the container, but it isn't activated. `pipenv run EXECUTABLE` can start an executable of that environment. We want to start `python`.

`-m sphinx.ext.intersphinx`
We run the intersphinx module as a "__main__" program. For that case the module provides code that can do a very simple dump of an link inventory. Not great, but works. 
Read about this in the Sphinx docs: [Showing all links of an Intersphinx mapping file()](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#showing-all-links-of-an-intersphinx-mapping-file)

`https://docs.typo3.org/c/typo3/cms-core/master/en-us/objects.inv`
This is the inventory we want to have downloaded and queried. In TYPO3 we are following the usual convention that it's named `objects.inv` and located in the root path of a manual.

`| grep 75625`
We pipe the output through `grep` and watch out for lines containing `75625`.

It seems that the first word is the desired label.

### About the inventory
Watch out: There are at least two lists of labels. One is for `:doc:…` linking and one is for `:ref:…`linking.

## Idea
It should be easy to add a function to our container that produces a proper json dump of such inventories.

**Comment by sypets** [comment]
That is really interesting. 

---

On a side note:

Abtout the label: I had already been thinking about a naming convention for the changelog label. That could be something that the [automatic changelog generator](https://forger.typo3.com/utility/rst) could already generate.

Using just the number is a great idea, I think (makes it simpler), but the number (which is the initial issue number) can have several entries.

**Comment by marble** [comment]
Keep in mind that ALL labels in a single manual have to be unique. Otherwise life continues, but they simply don't work.

**Comment by tmotyl** [comment]
related issue on the core side https://forge.typo3.org/issues/89330

**Comment by tmotyl** [comment]
ok, so do I read the decision correctly that we should not add the linking?
Then this issue as well as the issue on the core side should be closed.

**Comment by marble** [comment]
Linking to explicitely specified labels will probably be easer, because you see those links in the source. And if you (core team) add the `Targets` page, that we have in most other manuals, there would be a - looong - visible html page as well. On the other hand, linking to the document works, but its difficult to derive the slug.

**Comment by marble** [comment]
I have added the documentation proposed by this issue here in the "container manual" https://docs.typo3.org/m/typo3/t3docs-docker-render-documentation/draft/en-us/Solutions/decode-objects-inventory.html and left a link to this issue there.

**Comment by sypets** [comment]
The "do not link to changelog" came from me and was based on the observation that often people link to the changelog and not the "documentation". I personally don't have a problem if people link to the changelog - whether from the docs or elsewhere. What I do see as a problem though is  linking to the changelog and not the documentation if this is done on a large scale which effectively skews search results (because ranking on search engines is based partly on link structure, favoring results with lots of inlinks). 

I have seen links to the changelog and not the documentation a lot in "What's new slides", on "Skills display" and in documentation on other sites.

But, I think this should be addressed on several levels: Get changes to documentation made early (ideally, before release comes out), keep documentation updated etc. etc. 

So, I would not take this topic of linking to the changelog too religiously, it is one piece of several factors. 

One thing, I think we have come to an agreement on is that the documentation should contain everything necessary. It should not be: "Oh, btw there is a new feature, now read the changelog to find out more ...". The new feature (and documentation) should be fully documented in the docs. If this is the case, it will not be necessary to link to the changelog, but i case you do, that is ok. 

I added a section how to link to changelog to https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/HowToUpdateDocs.html
