### ISSUE TITLE
Address CGL indenting 3 space vs. 4 space issue?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#145]
The indent with 3 spaces has been in the documentation when I started. 

It has been revisited once, see TYPO3-Documentation/T3DocTeam#57. At that point there was not much participation, though it was voiced that some people were unhappy with current 3-spaces and would have liked to change it to 4. 

**The current status quo is that we have a mixture of 3 and 4 spaces in the docs, but most .editorconfig (in docs and core) contain the 3-space rule.** 

How should code _within_ code-blocks be indented? I actually saw it pointed out somewhere for our docs that code within code blocks should be indented with 3 spaces as well.

I will try to summarize the pros and cons, but for this some **help by others is requested**.

## Pro 3 spaces

* This is actually used in the sphinx start project (which is not really an argument but gives a hint to the source)
*  ... ?

## Pro 4 spaces

* Mostly the code-blocks: 4 spaces is used in core, at least for PHP and some others. Copy-pasting code must be done with a change in indenting level
* Editing files directly on GitHub does not give the option to use 3 spaces, only 2 and 4.
* ....

## Should we revisit?

* Currently I think it is not a huge problem, but having inconsistent CGL being followed makes some things more difficult. It also makes the docs look not well maintained. After all the effort we put in - not really very satisfactory.
* Not possible to apply automatic CGL checks in the docs currently, as is done in the core. This is something that might be done in the future. 

## Related

* TYPO3-Documentation/T3DocTeam#57

**Comment by linawolf** [comment]
The descistion for 4 spaces was made long since
