### ISSUE TITLE
Fix some formatting for indented text now styled as quote

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#146]
* [ ] https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/InlineCode.html#when-to-use-literal-code

![quote](https://user-images.githubusercontent.com/13206455/76389571-cf5f4800-636b-11ea-966f-e4c36a39109a.png)

* [ ] https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CommonPitfalls/Hyperlinks.html#correct-syntax

* [ ] https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CommonPitfalls/Indents.html#common-mistake-1-incorrect-indents

* [ ] https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CommonPitfalls/InlineStyle.html

* [ ] https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CommonPitfalls/Lists.html

**Comment by tomwarwick** [comment]
Closing issue at it appears that the indented quotes have been removed.
