### ISSUE TITLE
Find and document workflow for using custom image icons (arrows, numbers etc.) for screenshots

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#158]
Should work with inkscape and using SVG "symbol": https://softwarerecs.stackexchange.com/a/74602/39758

Related:

* #61

See also "old" information in Wiki: https://wiki.typo3.org/DocTeam/Official_Documentation_Screenshots

**Comment by susannemoog** [comment]
Hey @sypets - with the automatic screenshot project (as stated in another issue) I would leave the definition of how they should look and be used to that project and postpone this issue until we have a solution to that. Please feel free to reopen/comment if you see things differently.
