### ISSUE TITLE
Use `/Includes.txt` instead of relative path?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#159]
If I remember correctly, this is now possible:

`.. include /Includes.txt`

instead

`.. include:: ../../Includes.txt `

Confirm this and document it.

**Comment by marble** [comment]
Confirmed!

**Comment by sypets** [comment]
Thank you!

**Comment by sypets** [comment]
marble: 

> We should use Includes.rst.txt
> Nowadays we can use the absolute file reference /Includes.rst.txt where / means "root of the documentation", which in our case is <some_project_start_folder>/Documentation. This makes moving files much easier as relative paths like ../../ don't need to be taken care of.

https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1079

I will add a PR
