### ISSUE TITLE
Look at "The Good Docs Project" and possibly add to list of resources

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#163]
https://thegooddocsproject.dev/

This is our list of resources:

* https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingContent/Resources.html

Also, we might want to refer to some Styleguides. Martin recommends Microsoft Style guide, "The Good Docs Project" uses "Google Style guide",

**Comment by susannemoog** [comment]
I just checked our list of resources, their website and thought about what we could add. tbh I don't see anything we should necessarily add at the moment. I'm waiting for the TYPO3 writing guide to be published (which already contains a lot of guidance), but after that I wouldn't add even more resources. Imho we are already overwhelming the users with a lot information - the first blog post on our resources list alone is quite the read (it's very good, but still a lot to take in). 
If you have something concrete that is absolutely missing, please add a note here. Until then, I'll close this ticket.
