### ISSUE TITLE
Add documentation for rendering ViewHelper reference

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#173]
https://gist.github.com/marble/b02c753abf19368e0f34678601c157f3

**Comment by marble** [comment]
### Yes, please carry on the work
Yes, it would be great if this first version of a script gives reason to add it to a repository. I just didn't want to do that myself and I'm hoping others carry on with the script. That the whole idea of the permissive MIT license. I just don't want to be responsible, but do with it whatever you like. Just keep my name somewhere and - maybe - add more names.

### How this emerged
I hacked that script just up to the point that it worked for me. I don't make any claims about quality, neither quality of code nor quality or whether the script is doing the right things in the correct way.
- I wanted to give this a kick
- I wanted to save for my own memory what I had been fiddling with recently  after seeing a personal script of others
- I wanted to give this `whiptail` a try and see if it can be a basis for other Bash scripts. It looks like whiptail can make Bash scripts much more enjoyable.

**Comment by susannemoog** [comment]
The published view helper reference is not rendered by this script (it's using a github action instead) and I don't think we should document this script in some kind of "official" way. The github action can be found in the t3docs-ci-deploy repository. As Martin states that the script is not maintained, I think it's fine to keep it as gist for the time being until someone wants to take care of it in a more "reliable" manner (which should be a requirement for adding that to the docs). I'll close this issue for now, please reopen if you want to take care :)
