### ISSUE TITLE
Add required, optional, recommended for all settings in Settings.cfg

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#181]
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GeneralConventions/DirectoryFilenames.html#settings-cfg

**Comment by susannemoog** [comment]
@sypets will you take care yourself or should someone else take care of this issue?

**Comment by sypets** [comment]
Should be solved with pointing to Settings.cfg in docker repos, I guess. See https://github.com/TYPO3-Documentation/T3DocTeam/issues/167
