### ISSUE TITLE
Tip: Find PRs where my review is requested

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#207]
Tip worth going into the manual:

Martin Bless  9:58 AM
One more tip (what a  tippy day): I'm using this link to find pull requests where my review is wanted: https://github.com/pulls?q=is%3Aopen+user%3ATYPO3-Documentation+is%3Apr+review-requested%3Amarble

**Comment by sypets** [comment]
could be added to https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/GitHub/Index.html
