### ISSUE TITLE
Point out bad reST examples differently

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#210]
What do you think about:
https://github.com/TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument/pull/209#issuecomment-757519722 ?

![image](https://user-images.githubusercontent.com/307057/104159630-f9502380-53ef-11eb-9fdf-9694d805b8b9.png)

**Comment by sypets** [comment]
There is also a chapter dedicated to pointing out some of the problems and what to avoid: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/CommonPitfalls/Index.html This is linked to on the bottom of the page about lists: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/Lists.html

Perhaps it is best to not have examples with errors on the page with lists. I would find example 1 sufficient. I think it is better to keep it short - more people might read it that way.

**Comment by susannemoog** [comment]
@linawolf Do you agree that we should remove the example with the error and could you take care of that?

**Comment by linawolf** [comment]
I think it is important to show some bad examples here as this makes the rules easier to understand? At least this helped me when I was new to rst. Maybe we could format them a different way, however

**Comment by linawolf** [comment]
We removed them as they are not didatically helpfull
