### ISSUE TITLE
Explaining: How to document configuration values

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#238]
## Purpose

Maybe this is something that could and should be integrated.

## At Slack
Discussion is here at Slack: https://typo3.slack.com/archives/C028JEPJL/p1635695650154900?thread_ts=1635626876.153000&cid=C028JEPJL

**Comment by susannemoog** [comment]
@linawolf Can you check if and what should be documented here? From the slack thread I guess you are the one to ask.

**Comment by linawolf** [comment]
@susannemoog, @marble  Are you talking about the confval directive? 
There are still many effects about this one that it is not really fit to use so I wonder if we should promote it at all? I think in the context of TYPO3 we need a more hierarchical concept. I tried applying the confval directive to the TCA Reference, the results, however are just not satisfactory.

**Comment by linawolf** [comment]
confval ist documented
