### ISSUE TITLE
New DRC feature: Use custom namespaces for object descriptions

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#273]
This new and upcoming feature of the DRC should be described in How to document.
Check the description on this page, that should serve as a good starter.:
https://typo3-documentation.github.io/sphinx_typo3_theme_rendering_test/AddObjectType/Index.html

![grafik](https://user-images.githubusercontent.com/307057/161940162-3f6b3254-a779-42e3-9b36-021eadf71062.png)

And

![grafik](https://user-images.githubusercontent.com/307057/161940857-88938594-87e9-4293-98ff-d5133449a675.png)

**Comment by linawolf** [comment]
I think this is outdated
