### ISSUE TITLE
VCS README example - point out .rst format.

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#293]
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/UserRoundTrip.html#vcs-repository

Example README for VCS repository: please point out what format this is (.rst  or .md). It is possible to find this out but I think it should be stated more explicitly. People are not always aware of the distinction and even not aware that you **can** use .rst (and not .md) as README on GitHub / Gitlab etc.

Also, optionally also offer a Markdown example. Some (many) extension authors use Markdown as README and will/may not change this.

**Comment by linawolf** [comment]
I think this is resolved with the new rendering?
