### ISSUE TITLE
Add information about (preview) rendering

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#3]
This issue does not address the rendering on the documentation server. Here, we are primarily addressing what is relevant for people documenting to get a rendering preview of their changes. 

# Problem
Information about documentation rendering is in various places. Also, there are currently different methods to render, but usually only one method is explained without further information what is currently recommended. 

_Also, there are plans to overhaul the rendering on the server, which will also have an effect on how people will render.  Since this is not implement yet, we should take it into account, but document what is currently state-of-the-art._ 
https://docs.typo3.org/News/2018/Index.html#secret-plans-of-better-documentation-rendering

These are (currently) the methods to render documentation as preview:

1.  with docker container: https://github.com/t3docs/docker-render-documentation
2. ext:sphinx : https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/Documentation/Index.html
3. preview on Github (currently not documented anywhere)
4. Using Starter project: https://docs.typo3.org/Tips/TipOfTheDay/Index.html#how-to-start-documentation-for-your-typo3-extension
5.  (**outdated**) Local sphinx rendering toolchain (without docker): several places
  * https://docs.typo3.org/Tips/DocumentationWriters/Extensions/Index.html
 
# Possible solution

* [x] Add a chapter to "How to document" where docker method is explained as
recommended method
* [x] Link to [Readme for docker image on Github](https://github.com/t3docs/docker-render-documentation/blob/master/README.rst) from there
* [ ] Reduce other places in docs to a stub, remove outdated information and link to "How to document"
* [ ] Check if [Rendering guide ](https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/Index.html#start) is still up-to-date, consider if parts can be moved to "How to document" or "T3docsteam" or deleted and this guide taken offline

_Changes made here as proposed by @DanielSiepmann_ 

# To be clarified

* [ ] What are the recommended and supported methods (besides docker method)
* [ ] Is ext:sphinx method still recommended / supported?

**Comment by sypets** [comment]
@DanielSiepmann I agree with your comment, sounds like a good plan. 

I added _outdated_ to 5. because that only made sense when the docker image was not available (yet). 

There are some usecases which do not make the docker image a viable solution. So it's a question of  maintainability vs how much to support. I also tend to agree that it is best to have **one supported method which is very well maintained and documented**. 

One usecase where you might want to use different rendering method:

_changing docs directly on Github using the Web interface_ (here, the Github preview is only possible solution to get a preview of rendered result, as you said not 100% correct). I think, if you are serious about writing documentation, you will eventually switch to the docker method anyway. While editing online with the Github web interface seems convenient at first, it has too many drawbacks. While it looks like it will make it easier for people who are not familiar with the command line or docker, documenting various methods will only confuse people and make it harder to contribute in the long run. 

So, in direct conclusion editing directly on Github is not something we should actively promote anymore. It's something you can do for minor changes, but you have no way to test your changes properly (currently) using that workflow.

**Comment by DanielSiepmann** [comment]
So we should document the docker image and still Github, but add an information that Github is only recommended for first time contributions and fixing spelling and grammar issues.

**Comment by sypets** [comment]
I'm on it. 

See also 

#5

**Comment by sypets** [comment]
See new chapter in "How to document": https://docs.typo3.org/typo3cms/HowToDocument/RenderingDocs/Index.html
