### ISSUE TITLE
When to remove the version hints (for subsequent releases)?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#308]
At some point, the version hints may no longer be required and they add clutter. If this is decided, it could be documented, e.g. here:

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/CodingGuidelines.html#version-hints

My opinion is, it could be removed at the version of the version hint +2  (so, when added in 10, can be removed for 12). 

That means, people have 2 versions to adjust. Sometimes people upgrade several versions at once, but I assume those can be considered to be on a more "expert" level anyhow.

----

e.g. versionadded, versionchanged etc.

> New in version 10.0: [Feature: #84112 - Symfony dependency injection for core and extbase](https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Feature-84112-SymfonyDependencyInjectionForCoreAndExtbase.html)

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/DependencyInjection/Index.html

Here we have something which was added in 10.x, it is still there for 11.x and 12.

**Comment by linawolf** [comment]
We decide this on the fly depending on how important a topic is
