### ISSUE TITLE
We have 2 spelling lists and they are inconsistent (Backend / backend)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#317]
### Current behavior

2 spelling / glossary lists:

* in Docs "Writing Documentation": https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
* in "TYPO3 Community Language & Writing Guide": https://docs.typo3.org/m/typo3/writing-guide/main/en-us/writing-principles-and-guidelines/spelling-and-typo3-terminology.html

Also, there is the "[Content and Marketing Guide](https://docs.typo3.org/m/typo3/guide-contentandmarketing/main/en-us/Index.html)", another guide for writing and content.

List of inconsistencies:

| Docs: [Writing Documentation](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Index.html#)         | OSP: [TYPO3 Community Language & Writing Guide](https://docs.typo3.org/m/typo3/writing-guide/main/en-us/index.html) |
| -------------- | -------------------- |
| backend   | Backend          |
|frontend    | Frontend        |
| ... maybe more? | ...           |

Also, I think if words are not TYPO3 specific and there is only really 1 obvious spelling, they could be removed from the list::

For example:

* Apache
* API
* Linux
* MVC

### Expected behavior/output

Have one spelling / list of preferred terms list.

Or at least link to the other guide and unify the spelling (backend / Backend, Frontend / frontend).

### Additional context

The list in the documentation was there first. But the "Writing Guide" is more general so I think it might make more sense to maintain the list there and link to it.

What I don't like about the new "[TYPO3 Community Language & Writing Guide](https://docs.typo3.org/m/typo3/writing-guide/main/en-us/index.html)" is it has no "Edit on GitHub" button and does not encourage contribution. Also, I don't know why copyright is listed by "Open Strategy Partners and TYPO3 Community" and what the role of "Open Strategy Partners" is there. Is this a "community work" or is this out of our hands? Does this "belong to the people" (community)?

If other people or companies contribute to TYPO3 documentation (or core) work we don't list them either so this seems a bit unusual to me (if this is a community work, it looks like it is something in between).

Also, since the "[TYPO3 Community Language & Writing Guide](https://docs.typo3.org/m/typo3/writing-guide/main/en-us/index.html)" list was partially derived from the docs list with almost verbatim text (e.g. "system extension, not: 'sys extension' "), this is a derivative work and credit should be given due to license terms (see CC-BY license): https://creativecommons.org/licenses/by/4.0/

> © Copyright since 2021 by Open Strategy Partners and the TYPO3 Community

https://docs.typo3.org/m/typo3/writing-guide/main/en-us/writing-principles-and-guidelines/spelling-and-typo3-terminology.html#s

**Comment by brotkrueml** [comment]
"backend" and "frontend" are no proper nouns (at least as we use it), so they should be spelled lower cased IMHO.

**Comment by DavidBruchmann** [comment]
@brotkrueml about this long discussions happened already, so it's better to search for it rather than starting again from beginning. As far as I remember there  was a decision but I'm not sure if it was the documentation or the core team.

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
This says lowercase.

**Comment by DavidBruchmann** [comment]
I suspect that @flicstar could tell us about the connection to Open Strategy Partners, as she has listed it on her profile.

**Comment by flicstar** [comment]
Yep, definitely should be lower case unless at the start of a sentence. I think it's just upper case in the community writing guide because it's at the start of a line.

@sypets I'll pass on your concerns, feedback and questions to OSP.

**Comment by DavidBruchmann** [comment]
Thanks @flicstar for the quick response!

**Comment by flicstar** [comment]
It's taken me a long time to get around to this. Sorry about that! It fell off my radar.

I have removed the spelling and terms page from the TYPO3 Community Language & Writing Guide, and replaced it with a link to the spelling section of the Documentation content style guide. One source of truth is always best.

I'm waiting on Benni to publish the changes - it's a manual process.

**Comment by linawolf** [comment]
Seems like this is solved then
