### ISSUE TITLE
Deletion candidates

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#323]
These are some suggestions for deletion. I did not check this intensively.

Some pages are perhaps better suited for a blog post or to be maintained elsewhere:

* [x]  [Tools for Editing reST](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/ToolsEditRest/Index.html): this could be removed or shortened to basically: Install "reStructuredText Plugin" and "Editorconfig" plugin on PhpStorm
* [x]  [How to write good content](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingContent/Index.html)
* [ ] [Update documentation for new releases](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/HowToUpdateDocs.html) : I am not sure if this is currently being used or if we need such a page. If it should be kept, should check if up to date
* [x] [Guidelines for reviewing manuals](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/ReviewInformation.html): same as previous point: not sure if this is currently being used or if we need such a page. If it should be kept, should check if up to date

**Comment by linawolf** [comment]
We are still working on "Update documentation for new releases" the others have been removed
