### ISSUE TITLE
Add Words to Style Guide / Spelling Reference

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#36]
Add some terms that are commonly used in the docs to [Content Style Guide & Spelling](https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/ContentStyleGuide.html#spelling-reference) Only add terms where spelling is currently inconsistent or not obvious. 

* _Since spelling in title (headlines) follows different rules, here we focus on how words are spelled when not in title._
* Because the spelling can differ from context to context: Try to add additional context as example sentences, how the term might be used in a sentence or phrase or link to a good example for usage.

Current best choice in **bold**. 

* [x]  **"backend"** (alternate spellings, discouraged:   "back-end", "back end")
  * possible rule: "backend" if used as general backend,  "Backend", if used in the sense of **the** TYPO3 Backend
  * example: "When you log into the **backend**, make sure to ..."
  * see frontend in this list
* [x] "Code Sprint", **"code sprint"**
  * lowercase is commonly used, see https://en.wikipedia.org/wiki/Hackathon#Code_sprints
* [x] The product **Composer** is a proper noun and is capitalized, so use that unless you explicitly mean the command **composer** (see [Tools with Executables](https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/ContentStyleGuide.html#tools-with-executables))
* [x] **extension**. 
  * Example usage: "... includes all TYPO3 extensions that are uploaded to TER" (see [TYPO3 Explained: Extension Architecture: Extension Management](https://docs.typo3.org/typo3cms/CoreApiReference/ExtensionArchitecture/ExtensionManagement/Index.html)
* [x] **"Extension Manager"** or "extension manager"?
* [x] **Fluid**
* [x] **frontend** if used in the context of general backend,  "**Frontend**" if used in context of the TYPO3 Frontend, front-end, Front-End, Front End, front end (as noun)
  * differentiation spelling lowercase or uppercase: see backend in this list
  * reason for spelling as one word: "frontend" is most commonly used in docs. Though front-end / "front end" is more commonly used in dictionaries or wikipedia, it appears that "frontend" is not wrong and usage of various forms is common.
  * source: [Wikipedia](https://en.wikipedia.org/wiki/Front_and_back_ends) uses "front end" and "front-end"
  * source: [Merriam-Webster uses front end](https://www.merriam-webster.com/dictionary/front-end) (as noun)
  * TYPO3 docs uses various spellings, most common appears to be **frontend**:  see ["frontend" in Getting Started](https://docs.typo3.org/typo3cms/GettingStartedTutorial/GeneralPrinciples/BackendAndFrontend/Index.html), ["Frontend", "frontend" and "front-end" in TypoScriptReference](https://docs.typo3.org/typo3cms/TyposcriptReference/latest/AppendixA/Index.html)
  * see Discussion on ["English Language Usage Stackexchange"](https://english.stackexchange.com/questions/34447/is-it-front-end-frontend-or-front-end)
* [x]  **GitHub**
* [x] **"Introduction Package"** or "introduction package"
  * Example usage:  “Look for an introduction package to get started” vs “The official TYPO3 Introduction Package is a great place to start”
  * uppercase or lowercase depends on context 
* [x] Quickstart / Quick Start / quick start / **quickstart** 
  * source: [Wikipedia Quickstart guide](https://en.wikipedia.org/wiki/Quickstart_guide) lists "Quickstart" and "Quick Start" as spelling
  * example ["We have previously provided a Quickstart guide to"](https://ctovision.com/hadoop-quickstart-use-whirr-to-automate-standup-of-your-distributed-cluster-on-rackspace-2/)
* [x] **reST**
* [x] "Site Package", "site package", **"sitepackage"** 
  * source: [Sitepackage](https://sitepackagebuilder.com/)
  * source: [Site Package Tutorial](https://docs.typo3.org/typo3cms/SitePackageTutorial/Index.html) 
  * also: "site package extension", "sitepackage builder", etc. 
* [x] (the) **"TYPO3 Core"** or "TYPO3 core"
  * Example usage: "The TYPO3 Core comes with a number of icons that may be used in your extension."
* [x] *ViewHelper*, (not viewhelper, view helper)
   * Use viewhelper, unless you are referring to something that is explicitly spelled ViewHelper (e.g. the directory. 
* [x] see also #37

## Additional information

capitalization

The most problematic question here (besides the question of one word, two words or hyphenated words, e.g. front-end) is captitalization, e.g. backend or Backend: In general, the trend is to write lowercase, even for specific technical terms, e.g. the internet, see [The Verge: AP Style Guide will no longer capitalize internet](https://www.theverge.com/2016/4/2/11352744/ap-style-guide-will-no-longer-capitalize-internet). In the case of backend: menu is spelled lowercase, why should backend be capitalized?

## References

* https://www.grammarly.com/blog/capitalization-rules/
* [Guardian and Observer Styleguide](https://www.theguardian.com/guardian-observer-style-guide-c) : look under capital:

**Comment by mabolek** [comment]
Backend is a dictionary word, and not a name, so I would write it lowercase. When you say "logged in to the backend", it could be any backend, just as you can "log in to the online gaming platform". I would only use uppercase if I wanted to emphasize the (one and only) TYPO3 Backend.
