### ISSUE TITLE
How to spell anchor texts? 

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#46]
Should text in (link) anchor text be written with title capitalization or as in normal text?

Example: We link to "Spelling Reference" chapter in a manual. Usually this would be spelled "spelling refernce". Example text: "Please see the `<Spelling Reference>` for more information".

If title capitalization is allowed in anchor text, cross-referencing can be used without always writing out the anchor text, which makes it easier for editors (`:ref:`t3tca:some-label``)

**Comment by mabolek** [comment]
My two cents: Use title case. It's not "a(ny) spelling reference", but "the (one and only) Spelling Reference".

**Comment by sypets** [comment]
@mabolek Do you mean for this example or in general?

I noticed, on https://typo3.org, title case is often used as well. That would be the easiest. In favor of coming to a fast decision and wrapping this up, I will document this with "use title case" and am closing here.

**Comment by sypets** [comment]
Result: https://docs.typo3.org/typo3cms/HowToDocument/GeneralConventions/ContentStyleGuide.html#rules-for-anchor-text
