### ISSUE TITLE
Invalid properties project_*

### ISSUE THREAD

**Issue by xperseguers** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#463]
On

https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/Reference/GuidesXml.html

the table of contents and the various subsections speak of `project_*` settings. But the example at top clearly shows this is written with a dash, not an underscore.

I suspect (but cannot confirm right away) the same applies for `report-issue`

**Comment by garvinhicking** [comment]
Yes indeed, good catch, thank you! Created a PR :)
