### ISSUE TITLE
Chapter "Rendering docs" should go to the "How to render" guide

### ISSUE THREAD

**Issue by marble** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#8]
My idea is to have TWO guides like this:
1. How to write (https://docs.typo3.org/typo3cms/HowToDocument/)
2. How to render (https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/)

This chapter is currently in the wrong guide:
https://docs.typo3.org/typo3cms/HowToDocument/RenderingDocs/Index.html

**Comment by sypets** [comment]
What is the advantage of having several guides for documenting?

I think it is better to have everything about writing documentation in one guide. Makes it easier to find, makes it easier to search (especially with search working the way it does), you can give people starting with documentation **one link** and don't have to point them to several different places. 

Also, in this guide, there are dependancies: Contributing to documentation needs the section about rendering. Why point the people to another seperate guide (which isn't even up to date)? I think it is bad enough that there is also the rendering readme on Github: https://github.com/t3docs/docker-render-documentation  

Additionally to this:

* several things in https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/ are currently redundant and already documented elsewhere (e.g. information about highlighting: https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/UnderstandTheRendering/Highlighting/Index.html)
* some of the things in the rendering guide only concerns the team (e.g. [At the docs server](https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/AtTheDocsServer/Index.html) ). I think that could move to the t3Team documentation. 
* some things are seriously outdated: e.g. https://docs.typo3.org/typo3cms/RenderTYPO3DocumentationGuide/LocalRendering/UsingALocalToolchain/Index.html

**Conclusion**: My suggestion would be to move team-related and still relevant stuff from rendering guide to Team-document and remove this guide completely. 

When we talked about this on Slack a while back, more people were in favor of merging documentation related things into one guide as opposed to having several. I think it would be interesting to **ask them why** and take what they say seriously. It is not just a question of personal preferences: it is a question of what makes the documentation useful for the majority of the people. 

Additonally, the rendering doc is still marked as WIP and littered with "to be written". Do people read WIP manuals? I usually don't.
