### ISSUE TITLE
FAQ for new documentation rendering

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#91]
Here, we collect (and answer) open questions. Anyone can grab one of these open questions and add them to the docs. 

Please also see [FAQ on extensions.typo3.org](https://extensions.typo3.org/faq/). We might want to decide, where the information for extension authors should go ...

* [ ] on the [Migrate](https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Migrate.html) page it says I should publish my extension at extensions.typo3.org. I thought this is not required for doc rendering. Is it required at all? What's the advantage?
* [ ] I already have a README.rst (or .md) on GitHub (Gitlab, bitbucket etc.). What's the advantage of rendering the docs on docs.typo3.org?

## Done

* [x] Is it possible to highjack extension documentation? How do you make sure only the author of the extension publishes the documentation? **(see answer below)**
* [x] Is there a way to manually trigger docs rendering aside from a Git repository push? **(see answer below)**
* [x] "the new workflow also means that the documentation and the extension at TER are two separate, independent entities, correct? In theory you could have the documentation in GitHub (for example) and the extension (code) somewhere else (or not in Git at all). You just need to fire the webhook from GitHub/GitLab/Bitbucket to trigger the documentation, correct?" (see [Slack](https://typo3.slack.com/archives/C028JEPJL/p1559810819047800))
  * **answer**: yes
* [x] GitHub (or Gitlab, bitbucket) etc. already automatically render a README.rst (or .md). For TYPO3 documentation I am required to have extra documentation in `Documentation` folder. This means I have to maintain 2 documentation. Or not?

**Comment by Woeler** [comment]
Is it possible to highjack extension documentation? How do you make sure only the author of the extension publishes the documentation?
Answer: Documentation rendering is restricted to one repository per package. I.e. if I trigger documentation with a repository with vendor `myVendor` and package `myPackage`, then nobody else will be able to trigger documentation from a different repository with that exact vendor/package name combination. You could say this works on a first come first served basis. However, if someone with malicious intent registers a package first from a fake or wrong repository, we will have to correct this by hand. The original author should in that case notify us.

**Comment by sypets** [comment]
@Woeler Thanks for the texts. This is perfect. I now added a FAQ to the migrate page using your texts. Hope that's ok. See PR #96

**Comment by sypets** [comment]
done.
